name: Deploy webpage
on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build typescript
        uses: alexthemaster/action-build-typescript@v1.2.1
       
      - name: Deploy webpage
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: webpage
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
